### ISSUE TITLE
Anyway to improve an existing model without recreating a new one? (Machine Learning)

### ISSUE THREAD

**Issue by VincentV89** [Microsoft/Product-Recommendations#14]
Hi, is this solution able to improve an existing model without recreating a new model each time?

**Comment by natinimni** [comment]
Hi @VincentV89 
Changing\improving a model essentially means modifying the training parameters and\or changing the catalog\usage files – both option require re-training of the model. 
There is no way to re-train and replace an existent model, one must train a new model and potentially delete the old one.

What you can do, is to mark the newly trained model as the ‘**default**’ model, and so essentially change\improve the default model:

To get recommendation from the default model, simply use the keyword ‘default’ instead of the model id: “*GET /api/models/default/recommend*” 
Read more: [Get Item-To-Item Recommendations from the Default Model]( https://github.com/Microsoft/Product-Recommendations/blob/master/doc/api-reference.md#get-item-to-item-recommendations-from-the-default-model) and  [Get Personalized Recommendations from the Default Model]( https://github.com/Microsoft/Product-Recommendations/blob/master/doc/api-reference.md#get-personalized-recommendations-from-the-default-model)

To set a model as the default mode, simple call “*PUT /api/models/default?modelId=<id>*” with the model id.
Read more: [Set Default Model Id](https://github.com/Microsoft/Product-Recommendations/blob/master/doc/api-reference.md#set-default-model-id)

This way, you could train new models without changing the consuming code. 
I hope this addresses your scenario.
